//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
    }
}
